CREATE TABLE library_user
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(256) NOT NULL,
    last_name  VARCHAR(256) NOT NULL,
    email      VARCHAR(256) NOT NULL,
    password   VARCHAR(256) NOT NULL,
    role       VARCHAR(256) NOT NULL
);

CREATE TABLE book
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title        VARCHAR(256)                  NOT NULL,
    description  TEXT                          NOT NULL,
    page_number  INT CHECK ( page_number > 0 ) NOT NULL,
    year         INT                           NOT NULL,
    publisher_id BIGINT                        REFERENCES library_user (id) ON DELETE SET NULL
);