CREATE TABLE library_user
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name VARCHAR(256) NOT NULL,
    last_name  VARCHAR(256) NOT NULL,
    email      VARCHAR(256) NOT NULL,
    password   VARCHAR(256) NOT NULL,
    role       VARCHAR(256) NOT NULL
);